# all linters that not deprecate.

# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  tests: true
  timeout: 10m
  modules-download-mode: readonly

linters:
  enable:
    - depguard
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - exhaustruct
    - gochecknoglobals
    - goerr113
    - lll
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - tagalign
    - testpackage
    - tparallel
    - varnamelen
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - dupl

linters-settings:
  goconst:
    min-occurrences: 10
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  depguard:
    rules:
      controller_layer_only:
        list-mode: lax
        files:
          - "!**/internal/controller/http/**"
          - "!**/config/gin.go"
          - "!**/pkg/gouserhttp/**"
        deny:
          - pkg: github.com/gin-gonic/gin
            desc: "gin should only be used in controller http layer"
      repo_layer_only:
        list-mode: lax
        files:
          - "!**/internal/repo/**"
        deny:
          - pkg: github.com/jackc/pgx
            desc: "pgx should only be used in repo layer"
