// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/goproductgrpc/product.proto

package goproductgrpc

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqProductSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *ReqProductSearch) Reset() {
	*x = ReqProductSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqProductSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqProductSearch) ProtoMessage() {}

func (x *ReqProductSearch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqProductSearch.ProtoReflect.Descriptor instead.
func (*ReqProductSearch) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{0}
}

func (x *ReqProductSearch) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ResProductSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*ResProductDetail `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ResProductSearch) Reset() {
	*x = ResProductSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResProductSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResProductSearch) ProtoMessage() {}

func (x *ResProductSearch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResProductSearch.ProtoReflect.Descriptor instead.
func (*ResProductSearch) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{1}
}

func (x *ResProductSearch) GetProducts() []*ResProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

type ReqProductDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku  string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *ReqProductDetail) Reset() {
	*x = ReqProductDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqProductDetail) ProtoMessage() {}

func (x *ReqProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqProductDetail.ProtoReflect.Descriptor instead.
func (*ReqProductDetail) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{2}
}

func (x *ReqProductDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqProductDetail) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReqProductDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ResProductDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku         string               `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Slug        string               `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Name        string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Stock       int32                `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ResProductDetail) Reset() {
	*x = ResProductDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResProductDetail) ProtoMessage() {}

func (x *ResProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResProductDetail.ProtoReflect.Descriptor instead.
func (*ResProductDetail) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{3}
}

func (x *ResProductDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResProductDetail) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ResProductDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ResProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResProductDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResProductDetail) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ResProductDetail) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResProductDetail) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReqProductAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku         string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Slug        string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Stock       int32  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *ReqProductAdd) Reset() {
	*x = ReqProductAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqProductAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqProductAdd) ProtoMessage() {}

func (x *ReqProductAdd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqProductAdd.ProtoReflect.Descriptor instead.
func (*ReqProductAdd) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{4}
}

func (x *ReqProductAdd) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReqProductAdd) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ReqProductAdd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqProductAdd) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReqProductAdd) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ResProductAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResProductAdd) Reset() {
	*x = ResProductAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_goproductgrpc_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResProductAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResProductAdd) ProtoMessage() {}

func (x *ResProductAdd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_goproductgrpc_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResProductAdd.ProtoReflect.Descriptor instead.
func (*ResProductAdd) Descriptor() ([]byte, []int) {
	return file_pkg_goproductgrpc_product_proto_rawDescGZIP(), []int{5}
}

func (x *ResProductAdd) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pkg_goproductgrpc_product_proto protoreflect.FileDescriptor

var file_pkg_goproductgrpc_product_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x4f, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x22, 0x48, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x8a, 0x02, 0x0a, 0x10, 0x52,
	0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b,
	0x75, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x64, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x1f, 0x0a, 0x0d, 0x52,
	0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x64, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xed, 0x01, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x4c, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x1a, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x1a, 0x1f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x1c,
	0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x64, 0x64, 0x1a, 0x1c, 0x2e, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x64, 0x64, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x69, 0x64, 0x61, 0x79,
	0x61, 0x74, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_goproductgrpc_product_proto_rawDescOnce sync.Once
	file_pkg_goproductgrpc_product_proto_rawDescData = file_pkg_goproductgrpc_product_proto_rawDesc
)

func file_pkg_goproductgrpc_product_proto_rawDescGZIP() []byte {
	file_pkg_goproductgrpc_product_proto_rawDescOnce.Do(func() {
		file_pkg_goproductgrpc_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_goproductgrpc_product_proto_rawDescData)
	})
	return file_pkg_goproductgrpc_product_proto_rawDescData
}

var file_pkg_goproductgrpc_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_goproductgrpc_product_proto_goTypes = []interface{}{
	(*ReqProductSearch)(nil),    // 0: goproductgrpc.ReqProductSearch
	(*ResProductSearch)(nil),    // 1: goproductgrpc.ResProductSearch
	(*ReqProductDetail)(nil),    // 2: goproductgrpc.ReqProductDetail
	(*ResProductDetail)(nil),    // 3: goproductgrpc.ResProductDetail
	(*ReqProductAdd)(nil),       // 4: goproductgrpc.ReqProductAdd
	(*ResProductAdd)(nil),       // 5: goproductgrpc.ResProductAdd
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_pkg_goproductgrpc_product_proto_depIdxs = []int32{
	3, // 0: goproductgrpc.ResProductSearch.products:type_name -> goproductgrpc.ResProductDetail
	6, // 1: goproductgrpc.ResProductDetail.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: goproductgrpc.ResProductDetail.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: goproductgrpc.Product.Search:input_type -> goproductgrpc.ReqProductSearch
	2, // 4: goproductgrpc.Product.GetDetail:input_type -> goproductgrpc.ReqProductDetail
	4, // 5: goproductgrpc.Product.Add:input_type -> goproductgrpc.ReqProductAdd
	1, // 6: goproductgrpc.Product.Search:output_type -> goproductgrpc.ResProductSearch
	3, // 7: goproductgrpc.Product.GetDetail:output_type -> goproductgrpc.ResProductDetail
	5, // 8: goproductgrpc.Product.Add:output_type -> goproductgrpc.ResProductAdd
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_goproductgrpc_product_proto_init() }
func file_pkg_goproductgrpc_product_proto_init() {
	if File_pkg_goproductgrpc_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_goproductgrpc_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqProductSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_goproductgrpc_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResProductSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_goproductgrpc_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqProductDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_goproductgrpc_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResProductDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_goproductgrpc_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqProductAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_goproductgrpc_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResProductAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_goproductgrpc_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_goproductgrpc_product_proto_goTypes,
		DependencyIndexes: file_pkg_goproductgrpc_product_proto_depIdxs,
		MessageInfos:      file_pkg_goproductgrpc_product_proto_msgTypes,
	}.Build()
	File_pkg_goproductgrpc_product_proto = out.File
	file_pkg_goproductgrpc_product_proto_rawDesc = nil
	file_pkg_goproductgrpc_product_proto_goTypes = nil
	file_pkg_goproductgrpc_product_proto_depIdxs = nil
}
